"""hyperopt-kit: a lightweight hyperparameter optimization toolkit."""

from .evaluate import RunResult, available_strategies, compare_strategies, run_search
from .report import render_report, write_report
from .searchers import (
    CMAESParameters,
    GaussianProcess,
    ProductKernelDensity,
    Trial,
    adaptive_parzen,
    bayesian_search,
    bohb_log_density_ratio,
    bohb_propose,
    bohb_search,
    bohb_select_trials,
    cmaes_parameters,
    cmaes_search,
    cmaes_weights,
    expected_improvement,
    grid_search,
    hyperband_brackets,
    hyperband_search,
    random_search,
    random_successive_halving,
    select_halving_survivors,
    successive_halving,
    successive_halving_rungs,
    tpe_log_density_ratio,
    tpe_search,
    tpe_split,
)
from .spaces import Categorical, FloatRange, IntRange, Space, parse_space

__version__ = "0.1.0"

__all__ = [
    "CMAESParameters",
    "Categorical",
    "FloatRange",
    "GaussianProcess",
    "IntRange",
    "ProductKernelDensity",
    "RunResult",
    "Space",
    "Trial",
    "adaptive_parzen",
    "available_strategies",
    "bayesian_search",
    "bohb_log_density_ratio",
    "bohb_propose",
    "bohb_search",
    "bohb_select_trials",
    "cmaes_parameters",
    "cmaes_search",
    "cmaes_weights",
    "compare_strategies",
    "expected_improvement",
    "grid_search",
    "hyperband_brackets",
    "hyperband_search",
    "parse_space",
    "random_search",
    "random_successive_halving",
    "render_report",
    "run_search",
    "select_halving_survivors",
    "successive_halving",
    "successive_halving_rungs",
    "tpe_log_density_ratio",
    "tpe_search",
    "tpe_split",
    "write_report",
]
